version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_USER: Babalu
      MYSQL_PASSWORD: Babalu@12
      MYSQL_ROOT_PASSWORD: Babalu@21
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_database
      SPRING_DATASOURCE_USERNAME: Babalu
      SPRING_DATASOURCE_PASSWORD: Babalu@12
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
